[package]
name = "peff"
version = "0.1.0"
authors = ["hakbyte <spam@hakbyte.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.86"
argh = "0.1.12"
object = "0.36.3"
walkdir = "2.5.0"

[profile.release]
panic = "abort"
